LOCALES = {
    'ar': {
        'title': "سهم | محرك البحث الفائق للهاردات القديمة",
        'drive': "اختر القرص:",
        'btn_index': "⚡ فهرسة الهارد الآن",
        'status_ready': "حالة النظام: جاهز",
        'status_scanning': "جاري المسح وحساب الأحجام... انتظر ثواني",
        'search': "🔍 ابحث هنا:",
        'results': "المعروض: {} من {}",
        'filter_title': "تصفية نوعية",
        'all': "كل شيء 🌐",
        'folders': "مجلدات 📁",
        'images': "صور فقط 🖼️",
        'docs': "مستندات 📄",
        'videos': "فيديوهات 🎬",  
        'audios': "صوتيات 🎵",   
        'col_name': "اسم الملف / المجلد",
        'col_size': "الحجم",
        'col_path': "المسار بالكامل",
        'btn_open': "📁 فتح موقع الملف",
        'btn_delete': "🗑️ حذف نهائياً",
        'btn_fav': "⭐ إضافة للمفضلة",
        'btn_show_fav': "🌟 عرض المفضلة",
        'btn_load': "🔄 تحميل المزيد...",
        'alert_drive': "الرجاء اختيار القرص أولاً",
        'confirm_del': "هل أنت متأكد من حذف {} نهائياً؟",
        'fav_added': "تمت الإضافة للمفضلة بنجاح!"
    },
    'en': {
        'title': "Sahm | Ultra Fast File Finder",
        'drive': "Select Drive:",
        'btn_index': "⚡ Index Drive Now",
        'status_ready': "Status: Ready",
        'status_scanning': "Scanning & calculating sizes...",
        'search': "🔍 Search here:",
        'results': "Displayed: {} of {}",
        'filter_title': "Quick Filters",
        'all': "All Files 🌐",
        'folders': "Folders 📁",
        'images': "Images 🖼️",
        'docs': "Documents 📄",
        'videos': "Videos 🎬",    
        'audios': "Audios 🎵",    
        'col_name': "Name",
        'col_size': "Size",
        'col_path': "Full Path",
        'btn_open': "📁 Open Location",
        'btn_delete': "🗑️ Delete Permanently",
        'btn_fav': "⭐ Add to Fav",
        'btn_show_fav': "🌟 Show Favorites",
        'btn_load': "🔄 Load More...",
        'alert_drive': "Please select a drive first",
        'confirm_del': "Are you sure you want to delete {}?",
        'fav_added': "Added to favorites successfully!"
    },
    'fr': {
        'title': "Sahm | Recherche de Fichiers Ultra Rapide",
        'drive': "Disque:",
        'btn_index': "⚡ Indexer le Disque",
        'status_ready': "Statut: Prêt",
        'status_scanning': "Analyse et calcul des tailles...",
        'search': "🔍 Chercher ici:",
        'results': "Affiché: {} sur {}",
        'filter_title': "Filtres",
        'all': "Tout 🌐",
        'folders': "Dossiers 📁",
        'images': "Images 🖼️",
        'docs': "Documents 📄",
        'videos': "Vidéos 🎬",    
        'audios': "Audios 🎵",    
        'col_name': "Nom",
        'col_size': "Taille",
        'col_path': "Chemin Complet",
        'btn_open': "📁 Ouvrir l'emplacement",
        'btn_delete': "🗑️ Supprimer",
        'btn_fav': "⭐ Favoris",
        'btn_show_fav': "🌟 Voir les Favoris",
        'btn_load': "🔄 Charger plus...",
        'alert_drive': "Veuillez choisir un disque",
        'confirm_del': "Supprimer {} définitivement?",
        'fav_added': "Ajouté aux favoris avec succès!"
    }
}